language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install -qq libjpeg-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

notifications:
    emails:
        - roteshund+github@gmail.com
    on_failure: alwais
